chore(trading): market setup fixtures
vegaprotocol/console-test pull request #34
Opened 2023-07-26 12:34 UTC by bwallacee

2023-07-26 12:48 UTC, mattrussell36 requested changes
Dont see a problem with this. Though I'd probably try to lean into the pytest features and use fixtures for this

2023-07-26 12:48 UTC, mattrussell36 commented on marketFixtures/continuousMarket/continuousMarket.py
I believe the python convention is snake case.

2023-07-26 12:48 UTC, mattrussell36 commented on tests/order_match/test_order_match.py
> +    setup_opening_auction_market
Do you need to invoke the function?

2023-07-26 12:58 UTC, bwallacee commented on tests/order_match/test_order_match.py
> +    setup_opening_auction_market
Don't think we do, Will remove

2023-07-26 12:58 UTC, bwallacee commented on marketFixtures/continuousMarket/continuousMarket.py
Updated to snake case.

2023-07-27 06:24 UTC, daro-maj commented on market_fixtures/opening_auction_market/opening_auction_market.py
> +    submit_order(vega, "Key 1", market_id, "SIDE_BUY", 1, 110)
Do we need this ? Trade is only needed to switch to continuous mode

2023-07-27 09:24 UTC, bwallacee commented
I think for now this way is "ok" but we may want to look into creating a new conftest.py and having the setups moved to there.

2023-07-28 08:27 UTC, mattrussell36 approved these changes

2023-07-28 08:34 UTC, merged